namespace PaperRaker.Core.Enum
{
    public enum PaperType
    {
        Unknown,
        Article,
        Book,
        Chapter,
        Paper,
        Research,
        Dataset,
        Thesis,
        PostedContent,
        ProceddingsArticle,
        Standard,
        Component,
        ReferenceEntry,
        Report,
        Monograph,
        BookSet,
        BookSeries,
        BookPart,
        BookSection,
        Journal,
        JournalIssue,
        JournalVolume,
        StandardSeries,
        ReferenceBook,
        ReportSeries,
        Proceddings,
        Other
    }
}